### ISSUE TITLE
Action need to update to deal with CVE vulnerabilities 

### ISSUE THREAD

**Issue by gabriel-kohen-by** [Azure/get-keyvault-secrets#15]
Per:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

![image](https://user-images.githubusercontent.com/57095228/96893242-81113c00-1458-11eb-9f31-ec1b9b9d6e19.png)

**Comment by dakota-maker-by** [comment]
@N-Usha or anyone from the team have any update on this? The deadline is now November 16th and this would break our workflows entirely

**Comment by kf6kjg** [comment]
#13 should solve this ifnwhen it gets merged.

**Comment by surfraz** [comment]
Thanks for approving @romil07, please could you also merge this and create a new release so that we can use it.

**Comment by dakota-maker-by** [comment]
@romil07 @kf6kjg After bumping our version in our workflows to v1.1 I'm still running into the `set-env` errors. Any ideas on this?

![Screen Shot 2020-11-16 at 8 46 45 AM](https://user-images.githubusercontent.com/28930322/99266380-4f398e00-27e8-11eb-8820-6dca93e24d81.png)

**Comment by dakota-maker-by** [comment]
@romil07 @kf6kjg After looking into this, it seems this library is also using an old version of `azure-actions-webclient`, but I don't think upgrading just that will work either, as that library itself still has `@actions/core` as version `^1.1.3` in its own package.json, so I think to fully mitigate this the `azure-actions-webclient` package will need to be upgraded and released, then this library will have to consume that new change

**Comment by kf6kjg** [comment]
I was able to get this fixed in our fork.  The release processes here are a little strange: the release branches, where the tag is placed, have to have the fully updated node_modules colder committed.

To build I did this:

1. Create new `releases/v*` branch or move the existing. I did the latter.
2. Execute the following:

   ```sh
   npm ci
   npm run build
   git add -f node_modules AND_EVERYTHING_ELSE_THATS_UPDATED
   ```

   Note that the above is from memory so YMMV: my bash history didn't store my actions for some reason and I didn't write them down.
3. Commit the added changes and push the branch.
4. Tag the branch with the relevant version tags.
   Note that if you are creating `v1.2.3` you'll need to make sure that the commit has the both `v1` and `v1.2` tags - even if you have to move the tags from their previous location.  This is due to how GH Actions references versions: it only looks for the exact tag if that tag exists.

There are probably better strategies, but I was working off of reverse engineering the first release, not making it better.

**Comment by kf6kjg** [comment]
I see that you've got the tags and branch in place.  However I also see that you've not yet committed the updated node_modules folder to the release branch.  Until that happens it'll continue to use the old version of `@actions/core` and show the error.

**Comment by brianleppez** [comment]
@romil07 Any updates on when the new release is going to be pushed? This is breaking all my pipelines now.

**Comment by romil07** [comment]
@brianleppez I am working on this. Will do it today.

**Comment by romil07** [comment]
@brianleppez @kf6kjg @dakota-maker-by @surfraz @N-Usha @gabriel-kohen-by 
I have made the required changes. Can you please test again and let us know if any issues?

**Comment by ryan-theta** [comment]
@romil07 working now, thanks

**Comment by anpaz** [comment]
We're facing the same error, do you know if we need to explicitly update the Action to use v1.1, or will it pick it up automatically?

**Comment by kf6kjg** [comment]
@anpaz As long as your `uses` line ends with `@v1` it should pick it up automatically. If you specified `@v1.0` you'll have to change it explicitly.

**Comment by gabriel-kohen-by** [comment]
Thanks @romil07. Works like a charm

**Comment by brianleppez** [comment]
thanks @romil07. It worked.

**Comment by kanika1894** [comment]
This seems to be fixed, therefore, closing the issue.

**Comment by kanika1894** [comment]
Closing as this is fixed.
